driverClassname = com.mysql.cj.jdbc.Driver
url = jdbc:mysql://localhost:3306/lab_consumable?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
username = root
password = 080426
initialSize=5
maxActive=30
minIdle=5
maxWait=5000
timeBetweenEvictionRunsMillis=60000
minEvictableIdleTimeMillis=300000
removeAbandoned=true
removeAbandonedTimeout=60
logAbandoned=true
